### ISSUE TITLE
ftp.pbone.net issues installing OpenStack packages

### ISSUE THREAD

**Issue by ipilcher** [RHFieldProductManagement/openshift-aio#33]
Seeing a lot of errors like:

```
fatal: [node20]: FAILED! => {"changed": false, "msg": "Failed to download packages: python3-pyyaml-5.3-2.el8.x86_64: Cannot download, all mirrors were already tried without success", "results": []}
```

`/etc/yum.repos.d/openstack-victoria.repo` references `ftp.pbone.net` directly, rather than through a mirror list.  That repo file isn't owned by any RPM, so I'm guessing that the playbooks are simply creating it.  CentOS Stream 8 does have a `centos-release-openstack-victoria` package available in its `extras` repo, which does use a mirror list.  Could we use that?

**Comment by hgeaydem** [comment]
The issue there is that metalinks-provided mirror lists are not distro-independant  ... What would work for Centos Streams wont work for RHEL and Rocky whereas manually pointing to that centos streams repo works on all rhel-based distros. As I would very much like to avoid having to have per-OS definitions (also due to the fact that Ansible doesn't really make a difference between Centos and RHEL, and soon should also recognize Rocky as a RHEL-based distro, making it a nightmare to identify and fork code based on rhel flavors) 
Any ideas are welcome there ...

**Comment by ipilcher** [comment]
You probably can't just `dnf install centos-release-openstack-victoria`, but the repo file from that package includes the following repo:

```
[centos-openstack-victoria]
name=CentOS-$releasever - OpenStack victoria
#baseurl=http://mirror.centos.org/$contentdir/8-stream/cloud/$basearch/openstack-victoria/
mirrorlist=http://mirrorlist.centos.org/?release=8-stream&arch=$basearch&repo=cloud-openstack-victoria
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Cloud
module_hotfixes=1
```

It looks to me like that mirrorlist URL ought to work on any EL8 OS, as the only variable it contains is `$basearch` (and you could always hardcode `x86_64`).

**Comment by ipilcher** [comment]
FYI, I just tested this by replacing the `baseurl` line in `playbooks/roles/base_software/files/openstack-victoria.repo` with the `mirrorlist` line from above.  Worked just fine on CentOS Stream 8 in the lab.

**Comment by hgeaydem** [comment]
applied that fix to the latest version of the base_software role now (0.0.5) , please update roles if you're having this issue :)
